/* ============================================================
 * ai_inference.c
 * ============================================================
 * Wraps the C code generated by STM32Cube AI Studio (ST.AI / STAI
 * runtime - confirmed from network.h: STAI_NETWORK_MODEL_NAME "network",
 * origin model "anomaly_model", IN/OUT = 30 x float32, activations
 * 184 bytes, weights 4616 bytes / g_network_weights_array[577]).
 *
 * NOTE: This is the *new* STAI API, not the legacy ai_network_create_and_init/
 * ai_error API from your earlier draft - that's why those calls are gone.
 * ============================================================ */

#include "ai_inference.h"
#include <string.h>
#include <math.h>

#include "network.h"        /* generated STAI network API + STAI_NETWORK_* macros */
#include "network_data.h"   /* declares g_network_weights_array */

/* If your local stai.h names the sync-run enum differently
 * (e.g. STAI_RUN_MODE_SYNC instead of STAI_MODE_SYNC), change this line. */
#ifndef STAI_RUN_MODE_SYNC_NAME
#define STAI_RUN_MODE_SYNC_NAME  STAI_MODE_SYNC
#endif

/* ---- Sliding window state ---- */
static float s_window[WINDOW_SIZE][N_CHANNELS];
static uint16_t s_fill_count = 0;
static uint16_t s_write_idx = 0;

/* ---- STAI network context + buffers (static, no heap) ---- */
static uint8_t s_network_ctx[STAI_NETWORK_CONTEXT_SIZE]
    __attribute__((aligned(STAI_NETWORK_CONTEXT_ALIGNMENT)));

static uint8_t s_activations[STAI_NETWORK_ACTIVATION_1_SIZE_BYTES]
    __attribute__((aligned(STAI_NETWORK_ACTIVATION_1_ALIGNMENT)));

static float s_in_data[STAI_NETWORK_IN_1_SIZE]
    __attribute__((aligned(STAI_NETWORK_IN_1_ALIGNMENT)));
static float s_out_data[STAI_NETWORK_OUT_1_SIZE]
    __attribute__((aligned(STAI_NETWORK_OUT_1_ALIGNMENT)));

static stai_network *s_network = (stai_network *)s_network_ctx;
static bool s_network_ready = false;

/* Sanity check at compile time: your window/channel config must match
 * what the model was actually trained/generated for. */
#if (INPUT_DIM != STAI_NETWORK_IN_1_SIZE)
#error "INPUT_DIM (WINDOW_SIZE * N_CHANNELS) does not match STAI_NETWORK_IN_1_SIZE - check ai_inference.h against network.h"
#endif

bool ai_inference_init(void)
{
    s_fill_count = 0;
    s_write_idx = 0;
    s_network_ready = false;

    stai_return_code rc;
    stai_ptr act_ptrs[STAI_NETWORK_ACTIVATIONS_NUM];
    stai_ptr weight_ptrs[STAI_NETWORK_WEIGHTS_NUM];
    stai_ptr in_ptrs[STAI_NETWORK_IN_NUM];
    stai_ptr out_ptrs[STAI_NETWORK_OUT_NUM];

    rc = stai_network_init(s_network);
    if (rc != STAI_SUCCESS) {
        return false;
    }

    act_ptrs[0] = (stai_ptr)s_activations;
    rc = stai_network_set_activations(s_network, act_ptrs, STAI_NETWORK_ACTIVATIONS_NUM);
    if (rc != STAI_SUCCESS) {
        return false;
    }

    /* g_network_weights_array is 577 * sizeof(uint64_t) = 4616 bytes,
     * matching STAI_NETWORK_WEIGHTS_SIZE_BYTES exactly. */
    weight_ptrs[0] = (stai_ptr)g_network_weights_array;
    rc = stai_network_set_weights(s_network, weight_ptrs, STAI_NETWORK_WEIGHTS_NUM);
    if (rc != STAI_SUCCESS) {
        return false;
    }

    in_ptrs[0] = (stai_ptr)s_in_data;
    rc = stai_network_set_inputs(s_network, in_ptrs, STAI_NETWORK_IN_NUM);
    if (rc != STAI_SUCCESS) {
        return false;
    }

    out_ptrs[0] = (stai_ptr)s_out_data;
    rc = stai_network_set_outputs(s_network, out_ptrs, STAI_NETWORK_OUT_NUM);
    if (rc != STAI_SUCCESS) {
        return false;
    }

    s_network_ready = true;
    return true;
}

static void normalize_window(const float raw[WINDOW_SIZE][N_CHANNELS], float *out_flat)
{
    for (int w = 0; w < WINDOW_SIZE; w++) {
        for (int c = 0; c < N_CHANNELS; c++) {
            int idx = w * N_CHANNELS + c;
            out_flat[idx] = (raw[w][c] - feature_mean[idx]) / feature_std[idx];
        }
    }
}

bool ai_inference_update(float temperature_c, float vibration_rms_g,
                          float pressure_kpa, float *out_score, uint8_t *out_is_anomaly)
{
    s_window[s_write_idx][0] = temperature_c;
    s_window[s_write_idx][1] = vibration_rms_g;
    s_window[s_write_idx][2] = pressure_kpa;
    s_write_idx = (s_write_idx + 1) % WINDOW_SIZE;

    if (s_fill_count < WINDOW_SIZE) {
        s_fill_count++;
    }
    if (s_fill_count < WINDOW_SIZE) {
        return false; /* not enough samples yet for a full window */
    }

    /* Reconstruct window in chronological order starting from the
     * oldest sample (s_write_idx currently points at the oldest slot,
     * since it just wrapped around to where the next write will go). */
    float ordered[WINDOW_SIZE][N_CHANNELS];
    for (int i = 0; i < WINDOW_SIZE; i++) {
        int src = (s_write_idx + i) % WINDOW_SIZE;
        ordered[i][0] = s_window[src][0];
        ordered[i][1] = s_window[src][1];
        ordered[i][2] = s_window[src][2];
    }

    float input_flat[INPUT_DIM];
    normalize_window(ordered, input_flat);

    float output_flat[INPUT_DIM];

    if (!s_network_ready) {
        /* Network not initialized (ai_inference_init failed or wasn't
         * called) - fall back to passthrough so callers don't crash,
         * but this is not a valid inference result. */
        memcpy(output_flat, input_flat, sizeof(output_flat));
    } else {
        memcpy(s_in_data, input_flat, sizeof(s_in_data));

        stai_return_code rc = stai_network_run(s_network, STAI_RUN_MODE_SYNC_NAME);
        if (rc != STAI_SUCCESS) {
            return false;
        }

        memcpy(output_flat, s_out_data, sizeof(output_flat));
    }

    float mse = 0.0f;
    for (int i = 0; i < INPUT_DIM; i++) {
        float diff = output_flat[i] - input_flat[i];
        mse += diff * diff;
    }
    mse /= INPUT_DIM;

    *out_score = mse;
    *out_is_anomaly = (mse > ANOMALY_THRESHOLD) ? 1 : 0;
    return true;
}
