"""
train_anomaly_model.py
========================================================
Trains a small autoencoder for on-device vibration/temperature/
pressure anomaly detection, matching the simulated sensor data
generated by stm32_sensor_sim/Core/Src/main.c.

Approach: autoencoders for anomaly detection are trained ONLY on
normal data. At inference time, the model tries to reconstruct its
input; high reconstruction error means the input doesn't look like
anything the model saw during training -> anomaly.

Output:
  - anomaly_model.h5     (Keras model, import this into STM32Cube AI Studio)
  - anomaly_model.tflite (alternative format, also accepted)
  - prints normalization constants (mean/std) and the anomaly
    threshold you need to hardcode into the STM32 firmware.

Install requirements first:
  pip install tensorflow numpy --break-system-packages
========================================================
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras

# ---- Must match the STM32 simulation parameters exactly ----
WINDOW_SIZE = 10          # number of consecutive samples per window
N_CHANNELS = 3             # temperature_c, vibration_rms_g, pressure_kpa
INPUT_DIM = WINDOW_SIZE * N_CHANNELS   # 30
N_SAMPLES = 20000          # synthetic training samples to generate

SAMPLE_PERIOD_S = 0.5      # matches STM32 SAMPLE_PERIOD_MS = 500

def generate_normal_sample_sequence(n_samples, seed=0):
    """Reproduces the STM32 simulation formulas (normal operation only,
    no injected spikes) so the autoencoder learns what 'normal' looks like."""
    rng = np.random.default_rng(seed)
    t = np.arange(n_samples) * SAMPLE_PERIOD_S

    temperature = 45.0 + 5.0 * np.sin(t * 0.05) + rng.uniform(-1.5, 1.5, n_samples)
    vibration = 0.8 + 0.3 * np.sin(t * 0.3) + rng.uniform(-0.1, 0.1, n_samples)
    pressure = 101.3 + 0.5 * np.sin(t * 0.02) + rng.uniform(-0.2, 0.2, n_samples)

    return np.stack([temperature, vibration, pressure], axis=1)  # (n_samples, 3)


def make_windows(data, window_size):
    """Slides a window over the sequence, flattening each window to a
    single feature vector (matches how the STM32 will build its input)."""
    n = len(data) - window_size + 1
    windows = np.zeros((n, window_size * data.shape[1]), dtype=np.float32)
    for i in range(n):
        windows[i] = data[i:i + window_size].flatten()
    return windows


def build_autoencoder(input_dim):
    inputs = keras.Input(shape=(input_dim,))
    x = keras.layers.Dense(16, activation="relu")(inputs)
    x = keras.layers.Dense(4, activation="relu", name="bottleneck")(x)
    x = keras.layers.Dense(16, activation="relu")(x)
    outputs = keras.layers.Dense(input_dim, activation="linear")(x)
    model = keras.Model(inputs, outputs, name="vibration_autoencoder")
    model.compile(optimizer="adam", loss="mse")
    return model


def main():
    print("Generating synthetic normal-operation training data...")
    raw = generate_normal_sample_sequence(N_SAMPLES)
    windows = make_windows(raw, WINDOW_SIZE)

    # Normalize using training-set statistics. These exact mean/std
    # values must be hardcoded into the STM32 firmware so inference
    # input is normalized the same way at runtime.
    mean = windows.mean(axis=0)
    std = windows.std(axis=0) + 1e-6
    windows_norm = (windows - mean) / std

    split = int(0.9 * len(windows_norm))
    x_train, x_val = windows_norm[:split], windows_norm[split:]

    print(f"Training on {len(x_train)} windows, validating on {len(x_val)}...")
    model = build_autoencoder(INPUT_DIM)
    model.fit(x_train, x_train, validation_data=(x_val, x_val),
              epochs=30, batch_size=64, verbose=2)

    # Reconstruction error on validation (normal) data -> sets the
    # threshold above which the STM32 should flag an anomaly.
    recon = model.predict(x_val, verbose=0)
    mse_per_window = np.mean((recon - x_val) ** 2, axis=1)
    threshold = float(mse_per_window.mean() + 3 * mse_per_window.std())

    print("\n" + "=" * 60)
    print("COPY THESE VALUES INTO THE STM32 FIRMWARE (ai_inference.h)")
    print("=" * 60)
    print(f"#define WINDOW_SIZE  {WINDOW_SIZE}")
    print(f"#define N_CHANNELS   {N_CHANNELS}")
    print(f"#define INPUT_DIM    {INPUT_DIM}")
    print(f"#define ANOMALY_THRESHOLD  {threshold:.6f}f")
    print()
    print("static const float feature_mean[INPUT_DIM] = {")
    print(",\n".join(f"    {v:.6f}f" for v in mean))
    print("};")
    print()
    print("static const float feature_std[INPUT_DIM] = {")
    print(",\n".join(f"    {v:.6f}f" for v in std))
    print("};")
    print("=" * 60)

    model.save("anomaly_model.h5")
    print("\nSaved anomaly_model.h5")

    # Also export TFLite (float32, no quantization) - STM32Cube AI Studio
    # accepts both formats directly.
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert()
    with open("anomaly_model.tflite", "wb") as f:
        f.write(tflite_model)
    print("Saved anomaly_model.tflite")

    print("\nQuick sanity check - inject an anomaly and confirm it's flagged:")
    anomaly_window = raw[:WINDOW_SIZE].copy()
    anomaly_window[:, 1] += 5.0  # inject a large vibration spike
    anomaly_flat = ((anomaly_window.flatten() - mean) / std).reshape(1, -1)
    anomaly_recon = model.predict(anomaly_flat, verbose=0)
    anomaly_mse = float(np.mean((anomaly_recon - anomaly_flat) ** 2))
    print(f"  Injected-anomaly reconstruction MSE: {anomaly_mse:.6f} "
          f"({'ABOVE' if anomaly_mse > threshold else 'below'} threshold {threshold:.6f})")


if __name__ == "__main__":
    main()
