/* ============================================================
 * ai_inference.c
 * ============================================================
 * Wraps the C code generated by STM32Cube AI Studio.
 *
 * IMPORTANT - after you generate code in STM32Cube AI Studio:
 *   1. Copy the generated files (typically network.h, network.c,
 *      network_data.h, network_data.c, and the ai_platform/*
 *      runtime files) into your project - STM32Cube AI Studio's
 *      "Generate code" step tells you exactly where they land,
 *      or copy them under Core/Inc and Core/Src / Middlewares.
 *   2. Confirm the generated network's handle type and function
 *      prefix - STM32Cube AI Studio names these after your model
 *      name (here assumed to be "network", matching the default).
 *      If you named your model differently in the tool, do a
 *      find-and-replace of "network" with your actual model name
 *      in this file.
 *   3. Add the generated folder(s) to your project's include paths
 *      in STM32CubeIDE (Project Properties -> C/C++ Build -> Settings
 *      -> Include Paths).
 * ============================================================ */

#include "ai_inference.h"
#include <string.h>
#include <math.h>

/* --- Uncomment once the generated files are added to the project --- */
// #include "network.h"
// #include "network_data.h"

/* ---- Sliding window state ---- */
static float s_window[WINDOW_SIZE][N_CHANNELS];
static uint16_t s_fill_count = 0;
static uint16_t s_write_idx = 0;

/* ---- Generated network handle (uncomment once network.h is added) ---- */
// static ai_handle s_network = AI_HANDLE_NULL;
// AI_ALIGNED(4) static ai_u8 activations[AI_NETWORK_DATA_ACTIVATIONS_SIZE];
// AI_ALIGNED(4) static ai_float in_data[AI_NETWORK_IN_1_SIZE];
// AI_ALIGNED(4) static ai_float out_data[AI_NETWORK_OUT_1_SIZE];

bool ai_inference_init(void)
{
    s_fill_count = 0;
    s_write_idx = 0;

    /* --- Uncomment once network.h/network_data.h are in the project --- */
    // ai_network_params params;
    // const ai_handle acts[] = { activations };
    // ai_error err = ai_network_create_and_init(&s_network, acts, NULL);
    // if (err.type != AI_ERROR_NONE) {
    //     return false;
    // }
    // (void)params;

    return true; /* returns true even with the network stubbed out, so
                    the rest of the firmware compiles/runs before you've
                    generated and wired in the real model */
}

static void normalize_window(const float raw[WINDOW_SIZE][N_CHANNELS], float *out_flat)
{
    for (int w = 0; w < WINDOW_SIZE; w++) {
        for (int c = 0; c < N_CHANNELS; c++) {
            int idx = w * N_CHANNELS + c;
            out_flat[idx] = (raw[w][c] - feature_mean[idx]) / feature_std[idx];
        }
    }
}

bool ai_inference_update(float temperature_c, float vibration_rms_g,
                          float pressure_kpa, float *out_score, uint8_t *out_is_anomaly)
{
    s_window[s_write_idx][0] = temperature_c;
    s_window[s_write_idx][1] = vibration_rms_g;
    s_window[s_write_idx][2] = pressure_kpa;
    s_write_idx = (s_write_idx + 1) % WINDOW_SIZE;

    if (s_fill_count < WINDOW_SIZE) {
        s_fill_count++;
    }
    if (s_fill_count < WINDOW_SIZE) {
        return false; /* not enough samples yet for a full window */
    }

    /* Reconstruct window in chronological order starting from the
     * oldest sample (s_write_idx currently points at the oldest slot,
     * since it just wrapped around to where the next write will go). */
    float ordered[WINDOW_SIZE][N_CHANNELS];
    for (int i = 0; i < WINDOW_SIZE; i++) {
        int src = (s_write_idx + i) % WINDOW_SIZE;
        ordered[i][0] = s_window[src][0];
        ordered[i][1] = s_window[src][1];
        ordered[i][2] = s_window[src][2];
    }

    float input_flat[INPUT_DIM];
    normalize_window(ordered, input_flat);

    float output_flat[INPUT_DIM];

    /* --- Uncomment once network.h is generated and wired in --- */
    // memcpy(in_data, input_flat, sizeof(in_data));
    // ai_buffer *ai_input = ai_network_inputs_get(s_network, NULL);
    // ai_buffer *ai_output = ai_network_outputs_get(s_network, NULL);
    // ai_input[0].data = AI_HANDLE_PTR(in_data);
    // ai_output[0].data = AI_HANDLE_PTR(out_data);
    // ai_i32 n_batch = ai_network_run(s_network, ai_input, ai_output);
    // if (n_batch != 1) { return false; }
    // memcpy(output_flat, out_data, sizeof(output_flat));

    /* --- PLACEHOLDER until the real network is wired in: pass input
     * straight through so the pipeline is testable end-to-end before
     * you've generated the actual model. Reconstruction error will
     * always read ~0 until you uncomment the block above. --- */
    memcpy(output_flat, input_flat, sizeof(output_flat));

    float mse = 0.0f;
    for (int i = 0; i < INPUT_DIM; i++) {
        float diff = output_flat[i] - input_flat[i];
        mse += diff * diff;
    }
    mse /= INPUT_DIM;

    *out_score = mse;
    *out_is_anomaly = (mse > ANOMALY_THRESHOLD) ? 1 : 0;
    return true;
}
